name: Django Backend API CI/CD

on:
  push:
    branches: [ "main" ]
  

jobs:
  deploy:
    runs-on: self-hosted #자신의 서버의 러너로 실행
    steps:
      - name: Code Updates on
        run: |
          cd /home/lestl/quest_project
          git pull origin main #코드를 받아온다.

      - name: Backend Redploy
        run: |
          cd /home/lestl/quest_project
          # DB나 Nginx는 건드리지 않고 백엔드만 새로 빌드해서 갈아끼윰
          docker compose up -d --build backend
